; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Velocidad del monitor
monitor_speed = 115200

; --- CONFIGURACIÓN SEGURA (SIN MEMORIA EXTREMA) ---
; Quitamos las lineas de qio_opi y flash size por ahora.
; Si esto arranca, luego vemos como activar los 8MB de RAM.

build_flags = 
    ; Forzamos a usar el puerto COM físico (el de la izquierda o derecha según tu cable)
    -D ARDUINO_USB_CDC_ON_BOOT=0
    -D ARDUINO_USB_MODE=1